# Generated by Django 4.2.22 on 2025-06-05 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('available_slots', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='bookings',
            name='slots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.slots'),
        ),
        migrations.AlterField(
            model_name='slots',
            name='timings',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='slots',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.classes'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.classes'),
        ),
        migrations.DeleteModel(
            name='Classess',
        ),
    ]
