# Generated by Django 4.2.22 on 2025-06-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_classes_remove_bookings_available_slots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slots',
            old_name='class_name',
            new_name='class_id',
        ),
    ]
