# Generated by Django 4.2.22 on 2025-06-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_rename_timings_slots_end_timings_slots_start_timings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slots',
            old_name='class_id',
            new_name='classes_id',
        ),
    ]
