# Generated by Django 4.2.22 on 2025-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_rename_class_id_slots_classes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='available_slots',
            field=models.IntegerField(null=True),
        ),
    ]
