# Generated by Django 4.2.22 on 2025-06-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_classes_available_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='available_slots',
        ),
    ]
