# Generated by Django 4.2.22 on 2025-06-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_remove_classes_available_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slots',
            old_name='classes_id',
            new_name='classes',
        ),
    ]
